[package]
name = "sound_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15"
rodio = "0.17"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
hound = "3.5.0"
tonic = "0.10"
prost = "0.12"
tokio = { version = "1", features = ["full"] }


[build-dependencies]
tonic-build = "0.10"